- packages/ComponentLibrary/src/components/Modal/styles.ts
> Feature EPL-1478: Fixing styles sizes

- packages/ComponentLibrary/src/components/Input/Select/index.tsx
- packages/ComponentLibrary/src/components/Input/Select/style.ts
- packages/ComponentLibrary/src/components/NotificationItemAllStates/styles.ts
- packages/MainUI/src/screens/Home/index.tsx
- packages/MainUI/vite.config.ts
- packages/storybook/src/stories/Components/Tag/Tag.stories.tsx
Additional modifications include the creation of the Storybook for the Tag component. This update also integrates the previously missing color palette into the main project settings, ensuring consistent color usage across all components.
Below is an image based on what is implemented.
> Feature EPL-1615: [Storybook] - Tags + variants

- packages/ComponentLibrary/src/components/Input/TextInput/TextInputAutocomplete/SearchInputWithVoice/index.tsx
- packages/ComponentLibrary/src/components/Input/TextInput/TextInputAutocomplete/TextInputAutocomplete.mock.ts
- packages/ComponentLibrary/src/components/Input/TextInput/TextInputAutocomplete/TextInputAutocomplete.tsx
- packages/ComponentLibrary/src/components/Input/TextInput/TextInputBase/TextInputBase.styles.ts
- packages/MainUI/src/screens/Home/index.tsx
- packages/storybook/src/stories/Components/Input/TextInput/TextInputAutocomplete/SearchInputWithVoice/SearchInputWithVoice.stories.tsx
- packages/storybook/src/stories/Components/Input/TextInput/TextInputAutocomplete/TextInputAutocomplete.stories.tsx
- packages/storybook/src/stories/Components/Input/TextInput/TextInputAutocomplete/mock.ts
- packages/storybook/src/stories/Components/Input/TextInput/TextInputBase/InputPassword/InputPassword.stories.tsx
- packages/storybook/src/stories/Components/Input/TextInput/TextInputBase/TextInputBase.stories.tsx
In this task, the stories of the **3 (three) inputs** developed are attached.
> Feature EPL-1610 EPL-1606 EPL-1596: Add Inputs Stories

- packages/ComponentLibrary/src/components/ProfileModal/ProfileModal.tsx
- packages/ComponentLibrary/src/components/ProfileModal/ToggleSection/index.tsx
- packages/ComponentLibrary/src/components/ProfileModal/ToggleSection/types.ts
- packages/ComponentLibrary/src/components/ProfileModal/UserProfile.types.ts
- packages/storybook/src/stories/Components/ProfileModal/ProfileModal.stories.tsx
- packages/storybook/src/stories/Components/ToggleSection/ToggleSection.stories.tsx
- packages/storybook/src/stories/Components/ToggleSection/mock.tsx
> Feature EPL-1605: Add the password section & small fixs

- packages/ComponentLibrary/src/components/PrimaryTab/index.tsx
- packages/ComponentLibrary/src/components/PrimaryTab/styles.ts
- packages/ComponentLibrary/src/components/PrimaryTab/types.ts
- packages/ComponentLibrary/src/components/SecondaryTabs/index.tsx
- packages/storybook/src/stories/Components/PrimaryTab/PrimaryTab.stories.tsx
- packages/storybook/src/stories/Components/PrimaryTab/mock.tsx
- packages/storybook/yarn.lock
First model of the PrimaryTab Component
> Feature EPL-1724: First model of the PrimaryTab Component

- build.gradle
Fix spring boot version in build.gradle
> Feature ETP-175: Fix spring boot version

- build.gradle
Fix spring dependencies version
> Feature ETP-175: Fix spring dependencies version

- packages/ComponentLibrary/src/components/Breadcrums/index.tsx
- packages/ComponentLibrary/src/components/Breadcrums/styles.ts
- packages/ComponentLibrary/src/components/Breadcrums/types.ts
- packages/storybook/src/stories/Components/Breadcrums/Breadcrums.stories.tsx
- packages/storybook/src/stories/Components/Breadcrums/mock.tsx
First model of the breadcrum component
> Feature EPL-1727: First model of the Breadcrums component

- packages/ComponentLibrary/src/App.css
- packages/MainUI/package.json
- packages/MainUI/src/App.tsx
- packages/MainUI/src/main.tsx
- packages/MainUI/src/screens/Login/index.tsx
Upgraded react and react-dom to version 19.
Applied react upgrade codemods.
Added and setup react router
> Feature ETP-178: Upgrade to react 19 and add react router

- packages/ComponentLibrary/src/components/ModalDivider/index.tsx
- packages/ComponentLibrary/src/components/NotificationItem/styles.ts
- packages/ComponentLibrary/src/components/Tab/index.tsx
- packages/ComponentLibrary/src/components/Tab/styles.ts
- packages/ComponentLibrary/src/components/Tab/types.ts
- packages/ComponentLibrary/src/interfaces/index.ts
- packages/storybook/src/stories/Components/Tab/Tab.stories.tsx
- packages/storybook/src/stories/Components/Tab/mock.tsx
> Feature EPL-1729: Tab Navigation Component

- README.md
- packages/EtendoHookBinder/.env.template
- packages/EtendoHookBinder/src/api/client.ts
- packages/EtendoHookBinder/src/api/constants.ts
- packages/MainUI/.env.template
- Added required declarations to `constants.ts`
- Added .env.template
- Added "Setup environment" section to README
> Feature ETP-86: Global Variables for Application

- packages/EtendoHookBinder/src/api/client.ts
- packages/EtendoHookBinder/src/api/constants.ts
- packages/EtendoHookBinder/src/api/data-handler.ts
- packages/EtendoHookBinder/src/api/types.ts
This new module allows to create or update existing records through SWS
> Feature ETP-91: Add data handler module

- packages/ComponentLibrary/src/components/Forms/Login.tsx
- packages/ComponentLibrary/src/components/Forms/styles.ts
- packages/ComponentLibrary/src/components/index.ts
- packages/EtendoHookBinder/src/api/constants.ts
- packages/MainUI/src/App.tsx
- packages/MainUI/src/contexts/user.tsx
- packages/MainUI/src/hooks/useUserContext.ts
- packages/MainUI/src/screens/Login/index.tsx
- packages/MainUI/src/screens/Login/styles.ts
- packages/MainUI/src/utils/logger.ts
Added login screen and UserContext.
The UserContext will take care of the API login, redirections and also prevent accessing secured screens without a valid session 
[Grabación de pantalla desde 2024-08-20 14-34-54.webm](https://github.com/user-attachments/assets/832e3821-2fee-4b7d-8964-fea1e6936784)
> Feature ETP-87: Add login screen

- packages/ComponentLibrary/src/components/Table/index.tsx
- packages/EtendoHookBinder/src/api/client.ts
- packages/EtendoHookBinder/src/api/constants.ts
- packages/EtendoHookBinder/src/api/data-handler.ts
- packages/EtendoHookBinder/src/api/datasource.ts
- packages/EtendoHookBinder/src/api/metadata.ts
- packages/MainUI/src/contexts/metadata.tsx
- packages/MainUI/src/contexts/user.tsx
- packages/MainUI/src/hooks/useMenu.ts
- packages/MainUI/src/main.tsx
- packages/MainUI/src/screens/Home/types.ts
Feature ETP-244: Refactor metadata and datasource to use SWS
> Feature ETP-244: Refactor metadata and datasource to use SWS

- packages/ComponentLibrary/src/components/Forms/Login.tsx
- packages/MainUI/src/screens/Login/index.tsx
> Feature ETP-87: Improve login form UX.

- packages/ComponentLibrary/src/components/FormView/Sections/FormSection.tsx
- packages/ComponentLibrary/src/components/FormView/Sections/noteSection.tsx
- packages/ComponentLibrary/src/components/FormView/Sections/sectionRendered.tsx
- packages/ComponentLibrary/src/components/FormView/index.tsx
- packages/ComponentLibrary/src/components/FormView/styles.ts
- packages/ComponentLibrary/src/components/FormView/types.ts
- packages/ComponentLibrary/src/theme.ts
- packages/storybook/src/stories/Components/Table/mock.tsx
- packages/storybook/src/stories/Components/Table/types.ts
Note section component, and improvements to the structure of the form view
> Feature EPL-1754: Add first version of the Notes section

- packages/ComponentLibrary/src/components/BasicModal/index.tsx
- packages/ComponentLibrary/src/components/BasicModal/styles.ts
- packages/ComponentLibrary/src/components/BasicModal/types.ts
- packages/ComponentLibrary/src/components/RegisterModal/index.tsx
- packages/storybook/src/stories/Components/BasicModal/Modal.stories.tsx
An optional function through props to make the modal fullScreen
> Feature EPL-1747: Add Full screen function

- packages/ComponentLibrary/src/components/Drawer/DrawerSection/index.tsx
- packages/ComponentLibrary/src/components/Drawer/MenuTitle/index.tsx
- packages/ComponentLibrary/src/components/Drawer/styles.ts
- packages/EtendoHookBinder/src/api/constants.ts
- packages/EtendoHookBinder/src/api/metadata.ts
- packages/EtendoHookBinder/src/hooks/useWindow.ts
Feature ETP-237: Fix metadata integration
> Feature ETP-237: Fix metadata integration

- packages/ComponentLibrary/src/components/Drawer/DrawerSection/index.tsx
- packages/ComponentLibrary/src/components/Drawer/Header/index.tsx
- packages/ComponentLibrary/src/components/Drawer/MenuTitle/index.tsx
- packages/ComponentLibrary/src/components/Drawer/index.tsx
- packages/ComponentLibrary/src/components/Drawer/styles.ts
- packages/ComponentLibrary/src/components/Drawer/types.ts
> Feature ETP-332: Fix Drawer

- packages/MainUI/src/index.css
- packages/MainUI/src/screens/Table/Tabs.tsx
Feature ETP-268: Fix tabs name.
> Feature ETP-268: Fix tabs name.

- packages/EtendoHookBinder/src/api/constants.ts
- packages/MainUI/src/contexts/user.tsx
- packages/MainUI/src/hooks/useUserContext.ts
Feature ETP-398: Fix user being logged out after page refresh.
> Feature ETP-398: Fix user being logged out after page refresh.

- build.gradle
Feature ETP-429: Fix spring version
> Feature ETP-429: Fix spring version

- src/main/java/com/etendoerp/mainui/EtendoUI.java
- src/main/java/com/etendoerp/mainui/SPAController.java
- src/main/java/com/etendoerp/mainui/WebConfig.java
Feature ETP-469: Implement Single Page Application (SPA) Routing
> Feature ETP-469: Implement Single Page Application (SPA) Routing

- packages/ComponentLibrary/src/components/ProfileModal/ProfileModal.tsx
- packages/ComponentLibrary/src/components/ProfileModal/types.ts
- packages/EtendoHookBinder/src/api/types.ts
- packages/MainUI/src/components/FormView/selectors/QuantitySelector.tsx
- packages/MainUI/src/components/FormView/selectors/index.tsx
- packages/MainUI/src/components/FormView/types.ts
- packages/MainUI/src/screens/Form/types.ts
- packages/MainUI/src/utils/formUtils.ts
- packages/MainUI/src/utils/quantitySelectorUtil.tsx
- packages/storybook/src/stories/Components/ToggleSection/ToggleSection.stories.tsx
> Feature ETP-489: Quantity Selector

- packages/MainUI/src/components/navigation.tsx
- packages/MainUI/src/screens/Home/index.tsx
- packages/storybook/src/stories/Components/Nav/Nav.stories.tsx
- packages/storybook/src/stories/Components/Nav/types.ts
> Feature ETP-489: Fix build

- packages/ComponentLibrary/src/components/Breadcrums/styles.ts
- packages/ComponentLibrary/src/components/Nav/Nav.styles.ts
- packages/EtendoHookBinder/src/api/types.ts
- packages/MainUI/src/components/Breadcrums.tsx
- packages/MainUI/src/components/FormView/selectors/TableDirSelector.tsx
- packages/MainUI/src/components/layout.tsx
- packages/MainUI/src/components/styles.ts
> Feature EPL-1749: Breadcrums

- packages/ComponentLibrary/package.json
- packages/ComponentLibrary/src/components/Drawer/DrawerSection/index.tsx
- packages/ComponentLibrary/src/components/Drawer/types.ts
- packages/ComponentLibrary/src/components/ProfileModal/ProfileModal.tsx
- packages/ComponentLibrary/src/components/ProfileModal/UserProfile.tsx
- packages/MainUI/src/components/FormView/selectors/TableDirSelector.tsx
- packages/MainUI/src/components/SanityChecker/index.tsx
- packages/MainUI/src/components/navigation.tsx
- packages/MainUI/src/contexts/record.tsx
- packages/MainUI/src/main.tsx
- packages/MainUI/tsconfig.json
This PR fixes the runtime error we're facing in demo
> Feature ETP-547: Remove react-router-dom from ComponentLibrary.

- packages/MainUI/components/FormView/selectors/index.tsx
- packages/MainUI/components/SanityChecker/index.tsx
- packages/MainUI/screens/Form/types.ts
Feature ETP-596: Fix tabledir selector.
> Feature ETP-596: Fix tabledir selector.

- packages/ComponentLibrary/package.json
- packages/ComponentLibrary/src/components/Input/Select/index.tsx
- packages/ComponentLibrary/src/components/Input/Select/style.ts
- packages/ComponentLibrary/src/components/Input/TextInput/TextInputBase/TextInputBase.tsx
- packages/ComponentLibrary/src/components/RadioButton/index.tsx
- packages/ComponentLibrary/src/components/SearchModal/SubComponents/DefaultContent/styles.ts
- packages/ComponentLibrary/src/components/SearchModal/SubComponents/HeaderSection/styles.ts
- packages/ComponentLibrary/src/components/SearchModal/SubComponents/ItemContent/styles.ts
- packages/ComponentLibrary/src/components/SearchModal/SubComponents/SectionContent/styles.ts
- packages/ComponentLibrary/src/components/SecondaryTabs/components/TabLabel/index.tsx
- packages/ComponentLibrary/src/components/SecondaryTabs/components/TabLabel/styles.ts
- packages/ComponentLibrary/src/components/Table/TabNavigation/TabContent.tsx
- packages/ComponentLibrary/src/components/Tag/styles.ts
- packages/ComponentLibrary/src/components/Toggle/Toggle.styles.ts
- packages/ComponentLibrary/src/index.ts
- packages/ComponentLibrary/src/theme/index.ts
- packages/ComponentLibrary/tsconfig.node.json
- packages/ComponentLibrary/vite.config.ts
- packages/MainUI/components/FormView/selectors/styles.ts
Fix theme this includes typographys, tooltips, configurations, and make the Component Library build with vite for optimizations
> Feature ETP-623: Fix theme in MainUI

- packages/ComponentLibrary/src/utils/menuUtils.ts
Added Icon as const and passes to icon prop for menu tittle component to handle it
> Feature ETP-624: Recently viewed Icon fix

- packages/ComponentLibrary/src/components/Table/TabNavigation/styles.ts
- packages/MainUI/app/page.tsx
- packages/MainUI/screens/Home/index.tsx
- packages/MainUI/screens/Home/styles.ts
Fix home styles according to figma
> Feature ETP-626: Fix home styles

- package.json
> Feature ETP-629: Fix chromatic build.

- .github/workflows/builder-reviewer.yml
- package.json
Github Action to build automatically when a branch is pointing to develop
> Feature ETP-677: Github Action to build

- packages/MainUI/components/Table/index.tsx
- packages/MainUI/components/Table/styles.ts
- packages/MainUI/screens/Table/Tabs.tsx
- packages/MainUI/screens/Table/styles.ts
Improved table styles and behave such as overlapping of papers, jump-lines in header cells, action and sort buttons, toolbar removed and buttons of tab
> Feature ETP-711: Improved table styles and behave

- .github/workflows/builder-reviewer.yml
- packages/ComponentLibrary/src/components/Drawer/DrawerSection/index.tsx
- packages/ComponentLibrary/src/components/Drawer/styles.ts
- packages/MainUI/components/Table/index.tsx
- packages/MainUI/components/Table/styles.ts
- packages/MainUI/screens/Table/Tabs.tsx
- packages/MainUI/screens/Table/styles.ts
Limited the makeweight of the popper menu to prevent the overflow and fix some styles.
> Feature ETP-709: Fix Drawer overflow and styles

- packages/ComponentLibrary/src/components/Input/Select/index.tsx
- packages/ComponentLibrary/src/components/ProfileModal/ToggleSection/index.tsx
- packages/EtendoHookBinder/src/api/authentication.ts
- packages/EtendoHookBinder/src/api/constants.ts
- packages/EtendoHookBinder/src/api/role.ts
- packages/EtendoHookBinder/src/api/utils.ts
- packages/EtendoHookBinder/src/api/warehouse.ts
Feature ETP-712: Fix login response encoding issues.
> Feature ETP-712: Fix login response encoding issues.

- packages/MainUI/app/[id]/page.tsx
- packages/MainUI/app/layout.tsx
- packages/MainUI/screens/Form/index.tsx
Added the [id] rout into the app router structure for the static formview
> Feature/ETP-714: Added the view for static formview

- packages/ComponentLibrary/src/components/ProcessModal/index.tsx
- packages/ComponentLibrary/src/components/ProcessModal/types.ts
- packages/ComponentLibrary/src/components/ProfileModal/ProfileModal.tsx
- packages/ComponentLibrary/src/components/ProfileModal/ToggleSection/index.tsx
- packages/ComponentLibrary/src/components/ProfileModal/UserProfile.tsx
- packages/ComponentLibrary/src/components/ProfileModal/types.ts
- packages/ComponentLibrary/src/components/RegisterModal/index.tsx
- packages/ComponentLibrary/src/components/RegisterModal/types.ts
- packages/ComponentLibrary/src/components/StatusModal/index.tsx
- packages/ComponentLibrary/src/components/StatusModal/types.ts
- packages/ComponentLibrary/src/components/Table/ExpandMenu/index.tsx
- packages/ComponentLibrary/src/components/Table/Sidebar/SidebarContent.tsx
- packages/ComponentLibrary/src/components/Table/Sidebar/index.tsx
- packages/ComponentLibrary/src/components/Table/Sidebar/types.ts
- packages/ComponentLibrary/src/locales/types.ts
- packages/MainUI/components/Nav/Profile.tsx
- packages/MainUI/components/Nav/types.ts
- packages/MainUI/components/Toolbar/Toolbar.tsx
- packages/MainUI/components/Toolbar/types.ts
- packages/MainUI/components/navigation.tsx
- packages/MainUI/hooks/Toolbar/types.ts
- packages/MainUI/hooks/Toolbar/useProcessButton.ts
- packages/MainUI/hooks/types.ts
- packages/MainUI/screens/Home/index.tsx
- packages/storybook/src/stories/Components/StatusModal/StatusModal.stories.tsx
- packages/storybook/src/stories/Components/Table/types.ts
Refactor of the ComponentLibrary in order to not have cyclic dependencies between that workspace and the MainUi
> Feature ETP-855: Refactor of the ComponentLibrary

- packages/ComponentLibrary/src/components/SearchModal/index.tsx
- packages/EtendoHookBinder/src/api/types.ts
- packages/EtendoHookBinder/src/hooks/useDatasource.ts
- packages/MainUI/components/TabLevel.tsx
- packages/MainUI/components/Table/index.tsx
- packages/MainUI/components/Toolbar/SearchPortal.tsx
- packages/MainUI/components/Toolbar/Toolbar.tsx
- packages/MainUI/components/Toolbar/styles.ts
- packages/MainUI/components/Toolbar/types.ts
- packages/MainUI/contexts/searchContext.tsx
- packages/MainUI/hooks/Toolbar/useToolbarConfig.ts
> Feature ETP-1052: Toolbar Search feature for table 

- Dockerfile
Feature ETP-1053: Added missing env vars as arguments to dockerfile.
> Feature ETP-1053: Added missing env vars as arguments to dockerfile.

- packages/MainUI/components/Form/FormFieldGroup.tsx
Feature ETP-1058: Remove label also if field is not displayed.
> Feature ETP-1058: Remove label also if field is not displayed.

- package.json
- packages/ComponentLibrary/.eslintrc.cjs
- packages/ComponentLibrary/src/locales/en.ts
- packages/ComponentLibrary/src/locales/es.ts
- packages/EtendoHookBinder/src/api/datasource.ts
- packages/EtendoHookBinder/src/api/types.ts
- packages/MainUI/.eslintrc.json
- packages/MainUI/components/Table/index.tsx
- packages/MainUI/components/Table/top-toolbar/index.tsx
- packages/MainUI/components/Table/top-toolbar/styles.ts
- packages/MainUI/tsconfig.json
- pnpm-lock.yaml
Feature ETP-1166: Added initial filters toggle.
> Feature ETP-1166: Added initial filters toggle.

- packages/EtendoHookBinder/src/api/datasource.ts
- packages/EtendoHookBinder/src/hooks/useComboSelect.ts
- packages/EtendoHookBinder/src/hooks/useDatasource.ts
- packages/MainUI/components/Form/FormView/selectors/DatabaseSelect.tsx
- packages/MainUI/components/Form/FormView/selectors/MultiSelect/MultiSelector.tsx
- packages/MainUI/components/Form/FormView/selectors/SearchSelector.tsx
- packages/MainUI/components/Form/FormView/selectors/TableDirSelector.tsx
Feature ETP-1215: Fixed selectors datasource usage.
> Feature ETP-1215: Fixed selectors datasource usage.

- packages/EtendoHookBinder/src/api/types.ts
- packages/EtendoHookBinder/src/hooks/useDatasource.ts
- packages/EtendoHookBinder/src/utils/search-utils.ts
- packages/EtendoHookBinder/src/utils/types.ts
- packages/MainUI/components/Table/index.tsx
Global Search for windows without numerics
> Feature ETP-1178: Global Search

- packages/EtendoHookBinder/src/api/types.ts
- packages/EtendoHookBinder/src/hooks/useDatasource.ts
- packages/EtendoHookBinder/src/utils/metadata.ts
- packages/MainUI/components/Table/index.tsx
- packages/MainUI/components/Table/styles.ts
- packages/MainUI/components/Table/top-toolbar/index.tsx
- packages/MainUI/components/Table/top-toolbar/styles.ts
- packages/MainUI/components/Toolbar/SearchPortal.tsx
- packages/MainUI/components/Toolbar/types.ts
- packages/MainUI/contexts/metadata.tsx
> Feature ETP-1235: Multiselect in table and implicit filters

- packages/EtendoHookBinder/src/api/types.ts
- packages/EtendoHookBinder/src/hooks/useDatasource.ts
- packages/EtendoHookBinder/src/utils/metadata.ts
- packages/EtendoHookBinder/src/utils/search-utils.ts
- packages/MainUI/components/Table/index.tsx
> Feature ETP-1245: Add filtering in columns

- packages/EtendoHookBinder/src/api/datasource.ts
- packages/MainUI/components/Table/index.tsx
Resolved the access to user and role windows
> Feature ETP-1261: Fix role & user windows

- packages/ComponentLibrary/src/components/ProfileModal/UserProfile.tsx
- packages/ComponentLibrary/src/components/ProfileModal/styles.ts
- packages/MainUI/components/Toolbar/Toolbar.tsx
- packages/MainUI/hooks/Toolbar/useProcessExecution.ts
- packages/MainUI/next.config.ts
Fixs svgs that have '?url' at the end  such as user profile modal and uxs at the success process
> Feature ETP-1340: UI Fixs

- packages/EtendoHookBinder/src/utils/metadata.ts
- packages/MainUI/components/Table/index.tsx
- packages/MainUI/utils/tableColumns.ts
> Feature ETP-1444: Fix booleans display value

- packages/ComponentLibrary/src/components/Widgets/TabWidget.tsx
- packages/ComponentLibrary/src/components/Widgets/types.ts
- packages/MainUI/screens/Home/index.tsx
- packages/MainUI/screens/Home/styles.ts
- packages/storybook/src/stories/Components/Table/mockWidget.tsx
> Feature ETP-1445: Add a dashboard mocked at home screen

- packages/ComponentLibrary/src/components/ConfigurationModal/index.tsx
- packages/ComponentLibrary/src/components/Input/TextInput/TextInputAutocomplete/SearchInputWithVoice/index.tsx
- packages/ComponentLibrary/src/components/NotificationsButton/index.tsx
- packages/ComponentLibrary/src/components/Waterfall/WaterfallModal.tsx
- packages/MainUI/components/layout.tsx
- packages/MainUI/components/navigation.tsx
> Feature ETP-1504: Disabled unfinished features from navbar

- packages/ComponentLibrary/src/components/Drawer/DrawerSection/index.tsx
- packages/ComponentLibrary/src/components/Drawer/MenuTitle/index.tsx
- packages/ComponentLibrary/src/components/Drawer/Search/index.tsx
- packages/ComponentLibrary/src/components/Drawer/index.tsx
- packages/ComponentLibrary/src/components/Drawer/styles.ts
- packages/ComponentLibrary/src/components/Drawer/types.ts
- packages/ComponentLibrary/src/components/ProfileModal/ToggleSection/index.tsx
- packages/ComponentLibrary/src/locales/en.ts
- packages/ComponentLibrary/src/locales/es.ts
- packages/ComponentLibrary/src/utils/clickAway.tsx
- packages/MainUI/app/styles/global.css
- packages/MainUI/components/navigation.tsx
> Feature ETP-1523: Optimized sidebar performance

- packages/MainUI/contexts/user.tsx
Feature ETP-1500: Fixed reloading loop
> Feature ETP-1500: Fixed reloading loop

- packages/ComponentLibrary/src/components/Input/TextInput/TextInputAutocomplete/SearchInputWithVoice/index.tsx
- packages/ComponentLibrary/src/components/Nav/Nav.styles.ts
- packages/ComponentLibrary/src/components/Nav/Nav.tsx
- packages/MainUI/components/navigation.tsx
> Feature ETP-1583: Add disabled styles for input in navbar

- packages/ComponentLibrary/src/components/Input/TextInput/TextInputAutocomplete/TextInputAutocomplete.tsx
- packages/ComponentLibrary/src/utils/searchUtils.tsx
Feature ETP-1594: Fixed drawer search
> Feature ETP-1594: Fixed drawer search

- packages/EtendoHookBinder/src/api/metadata.ts
- packages/EtendoHookBinder/src/api/types.ts
- packages/MainUI/components/Nav/Profile.tsx
- packages/MainUI/contexts/language.tsx
- packages/MainUI/contexts/metadata.tsx
- packages/MainUI/contexts/types.ts
Added labels and getLabel to LanguageContext.
> Feature ETP-1633: Added labels and getLabel to LanguageContext.

- packages/MainUI/components/Sidebar.tsx
- packages/MainUI/hooks/Toolbar/useToolbarConfig.ts
Feature ETP-1581: Fixed URL windowId parameter.
> Feature ETP-1581: Fixed URL windowId parameter.

- packages/MainUI/components/window/Tab.tsx
- packages/MainUI/hooks/useDatasource.ts
Feature ETP-1700: Records in the subtab are not cleaned
> Feature ETP-1700: Records in the subtab are not cleaned

- packages/ComponentLibrary/src/components/Drawer/DrawerSection/index.tsx
- packages/ComponentLibrary/src/components/Drawer/MenuTitle/index.tsx
- packages/ComponentLibrary/src/components/Drawer/index.tsx
- packages/MainUI/app/styles/global.css
> Feature ETP-1833: Fix Collapsed Drawer [Styles]

- packages/ComponentLibrary/src/components/Copilot/ContextPreview/index.tsx
- packages/ComponentLibrary/src/components/Copilot/CopilotPopup/ChatInterface.tsx
- packages/ComponentLibrary/src/components/Copilot/CopilotPopup/index.tsx
- packages/ComponentLibrary/src/components/Copilot/MessageComponents/MessageInput.tsx
- packages/ComponentLibrary/src/components/Copilot/MessageComponents/MessageList.tsx
- packages/ComponentLibrary/src/components/Copilot/types.ts
- packages/ComponentLibrary/src/components/index.ts
- packages/ComponentLibrary/src/locales/en.ts
- packages/ComponentLibrary/src/locales/es.ts
- packages/MainUI/app/styles/global.css
- packages/MainUI/components/Toolbar/buttonConfigs.tsx
- packages/MainUI/components/navigation.tsx
- packages/MainUI/hooks/Toolbar/useToolbarConfig.ts
- packages/MainUI/hooks/types.ts
- packages/MainUI/hooks/useRecordContext.ts
- packages/MainUI/utils/contextUtils.ts
- packages/api-client/src/api/copilot/constants.ts
> Feature ETP-1822: Implementation of Copilot Context Button

- .gitignore
- packages/MainUI/app/api/_test-utils/datasource-integration-commons.ts
- packages/MainUI/app/api/_utils/sessionStore.ts
- packages/MainUI/app/api/datasource/[entity]/__tests__/invoice-save.integration.test.ts
- packages/MainUI/app/api/datasource/[entity]/__tests__/missing-csrf.integration.test.ts
- packages/MainUI/app/api/datasource/[entity]/__tests__/route.test.ts
- packages/MainUI/app/api/datasource/[entity]/__tests__/save-auth-propagation.integration.test.ts
- packages/MainUI/app/api/datasource/[entity]/route.ts
- packages/MainUI/app/api/datasource/route.ts
- packages/MainUI/app/api/erp/[...slug]/__tests__/route.slug.integration.test.ts
- packages/MainUI/app/api/erp/[...slug]/route.ts
This pull request introduces improvements to CSRF token handling, authentication propagation, and test reliability for ERP datasource and proxy API routes. The changes ensure that CSRF tokens are securely generated, properly injected into request bodies, and consistently propagated through headers for both cached and non-cached requests. Test utilities and integration tests are updated for clarity and correctness, and type signatures are made more robust for Next.js compatibility.
**CSRF token management and propagation:**
* Added a secure `generateCsrfToken` function in `sessionStore.ts` and updated `setErpSessionCookie` to generate a CSRF token if none is provided, ensuring every session has a valid token. [[1]](diffhunk://#diff-6ce0dbe7015a7c2bbde13f50d7e95f94989ae99e27c68a5bbbf4d75e841 …
> Feature ETP-2071: Include CSRF token as header

- pipelines/utils/sonarUtils.groovy
- Added handling for cases where coverage is 0 or no measures exist.
- Enhanced error messages for better clarity on coverage retrieval failures.
> Feature ETP-2374: Improve coverage retrieval logic in sonarUtils.groovy
